const express = require('express');
const router = express.Router();
const pool = require('../db');

// Get Reviews for a Product
router.get("/product-reviews/:productId", async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT r.*, c.name as customer_name, c.profile_image
       FROM reviews r
       JOIN customers c ON r.customer_id = c.customer_id
       WHERE r.product_id = $1
       ORDER BY r.created_at DESC`,
      [req.params.productId]
    );
    res.json(result.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Error fetching reviews" });
  }
});

router.get("/api/reviews/:product_id", async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT r.*, c.name as customer_name, c.profile_image
       FROM reviews r
       JOIN customers c ON r.customer_id = c.customer_id
       WHERE r.product_id = $1
       ORDER BY r.created_at DESC`,
      [req.params.product_id]
    );
    res.json(result.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Error fetching reviews" });
  }
});

// Post a Review
router.post("/add-review", async (req, res) => {
  console.log("Adding review:", req.body);
  const { customerId, productId, rating, title, body, imageUrl, orderItemId } = req.body;
  try {
    // Note: review_id is generated by a database trigger
    const insertRes = await pool.query(
      `INSERT INTO reviews (customer_id, product_id, rating, title, body, image_url, order_item_id)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING *`,
      [customerId, productId, rating, title, body, imageUrl || null, orderItemId || null]
    );

    const newReview = insertRes.rows[0];
    
    // Fetch customer info to return a complete review object for the UI
    const custRes = await pool.query("SELECT name as customer_name, profile_image FROM customers WHERE customer_id = $1", [customerId]);
    const responseData = { ...newReview, ...custRes.rows[0] };

    res.json(responseData);
  } catch (err) {
    console.error("Error in add-review:", err.message);
    res.status(500).json({ message: "Error posting review: " + err.message });
  }
});

// Also support /api/reviews for compatibility
router.post("/api/reviews", async (req, res) => {
  console.log("Adding review (API):", req.body);
  const { customer_id, product_id, rating, title, body, images, order_item_id } = req.body;
  try {
    const imgUrl = (images && images.length > 0) ? images[0] : null;

    const insertRes = await pool.query(
      `INSERT INTO reviews (customer_id, product_id, rating, title, body, image_url, order_item_id)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING *`,
      [customer_id, product_id, rating, title, body, imgUrl, order_item_id || null]
    );

    const newReview = insertRes.rows[0];
    const custRes = await pool.query("SELECT name as customer_name, profile_image FROM customers WHERE customer_id = $1", [customer_id]);
    const responseData = { ...newReview, ...custRes.rows[0] };

    res.json(responseData);
  } catch (err) {
    console.error("Error in api/reviews:", err.message);
    res.status(500).json({ message: "Error posting review" });
  }
});

// Get Reviews for a Seller's Products
router.get("/seller-reviews/:sellerId", async (req, res) => {
  try {
    const { sellerId } = req.params;
    
    // Fetch all reviews for this seller's products
    const result = await pool.query(
      `SELECT r.*, c.name as customer_name, c.profile_image, p.name as product_name, p.images as product_images
       FROM reviews r
       JOIN products p ON r.product_id = p.product_id
       LEFT JOIN customers c ON r.customer_id = c.customer_id
       WHERE p.seller_id = $1
       ORDER BY r.created_at DESC`,
      [sellerId]
    );

    res.json(result.rows);
  } catch (err) {
    console.error("Error fetching seller reviews:", err);
    res.status(500).json({ message: "Error fetching seller reviews" });
  }
});

module.exports = router;
